name: Node.js CI

on:
  push:
    branches: [ "main" ]
    tags:
     - '*'

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Build
      run: |
        npm install
        npm run-script build
        tar -cvzf release.tar.gz --exclude='*.map' -C build .
        tar -cvzf release-with-maps.tar.gz -C build .
    - name: GH Release
      uses: softprops/action-gh-release@v0.1.14
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          release.tar.gz
          release-with-maps.tar.gz
    - name: Publish
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
